"use strict";

import "./linq.spec";
import "./modules/where.spec";
import "./modules/take.spec";
import "./modules/asEnumerable.spec";
import "./modules/select.spec";
import "./modules/toArray.spec";
import "./modules/utils.spec";
import "./modules/orderBy.spec";
import "./modules/orderByDescending.spec";
import "./modules/concat.spec";
import "./modules/range.spec";
import "./modules/empty.spec";
import "./modules/repeat.spec";
import "./modules/all.spec"
import "./modules/any.spec"
import "./modules/count.spec"
import "./modules/defaultIfEmpty.spec"
import "./modules/first.spec"
import "./modules/firstOrDefault.spec"
import "./modules/last.spec"
import "./modules/lastOrDefault.spec"
import "./modules/single.spec"
import "./modules/singleOrDefault.spec"